### ISSUE TITLE
Make logback-spike a Top Level Project

### ISSUE THREAD

**Issue by schnatterer** [thekua/Sample-Code#3]
Hi @thekua,

logback-spike is really helpful! There are not many solutions out there to unit test logging. I have found none that is as easy to use. Thanks for sharing!

The downside of logback-spike: It cannot be used out of the box as maven dependency. So could you please move it from `Sample-Code/java/logback-spike` to a top level project like `logback-spike` or rename this project and move logback-spike to the root directory?

This way it could be used with [jitpack ](https://www.jitpack.io/#thekua/Sample-Code) like so

```xml
	<dependency>
	    <groupId>com.github.thekua</groupId>
	    <artifactId>logback-spike</artifactId>
	    <version>-SNAPSHOT</version>
	</dependency>
````

Maven Central or JCenter would be even better, of course ;-)

**Comment by thekua** [comment]
Hi! I'm glad that you found it useful. 

The idea of the spike wasn't really to turn this into a key dependency for your project, or to maintain this an opensource project (I won't be able to commit the time to it). 

If you like it, I'd suggest that you copy the very simple clasess into your project. That way, you can make any changes you need to it on demand - rather than wait for an external dependency.
